# Generated by Django 6.1 on 2026-08-15 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiMonitorState',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_monitor_state',
            },
        ),
        migrations.CreateModel(
            name='AnalyticalReports',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('run_id', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'analytical_reports',
                'indexes': [models.Index(fields=['run_id'], name='analytical__run_id_dfe60d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=50)),
                ('resource', models.CharField(blank=True, max_length=50, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'audit_trail',
                'indexes': [models.Index(fields=['user_id'], name='audit_trail_user_id_acf306_idx'), models.Index(fields=['action'], name='audit_trail_action_5388db_idx'), models.Index(fields=['created_at'], name='audit_trail_created_9370d9_idx'), models.Index(fields=['session_id'], name='audit_trail_session_9556c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CyberIncidents',
            fields=[
                ('incident_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('severity', models.CharField(default='Medium', max_length=20)),
                ('category', models.CharField(default='Unknown', max_length=50)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cyber_incidents',
                'indexes': [models.Index(fields=['severity'], name='cyber_incid_severit_fb57c2_idx'), models.Index(fields=['status'], name='cyber_incid_status_b8aaff_idx'), models.Index(fields=['category'], name='cyber_incid_categor_57a5e0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('severity__in', ['Low', 'Medium', 'High', 'Critical'])), name='cyber_incidents_severity_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['Open', 'In Progress', 'Resolved', 'Closed'])), name='cyber_incidents_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='DatasetsMetadata',
            fields=[
                ('dataset_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rows', models.IntegerField(db_column='row_count', default=0)),
                ('columns', models.IntegerField(db_column='column_count', default=0)),
                ('uploaded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'datasets_metadata',
                'indexes': [models.Index(fields=['uploaded_by'], name='datasets_me_uploade_8e824b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rows__gte', 0)), name='datasets_metadata_rows_valid'), models.CheckConstraint(condition=models.Q(('columns__gte', 0)), name='datasets_metadata_columns_valid')],
            },
        ),
        migrations.CreateModel(
            name='ItTickets',
            fields=[
                ('ticket_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Open', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField()),
                ('resolution_time_hours', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'it_tickets',
                'indexes': [models.Index(fields=['priority'], name='it_tickets_priorit_0e4b6c_idx'), models.Index(fields=['status'], name='it_tickets_status_9ed334_idx'), models.Index(fields=['assigned_to'], name='it_tickets_assigne_bfa434_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('priority__in', ['Low', 'Medium', 'High', 'Critical'])), name='it_tickets_priority_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['Open', 'In Progress', 'Resolved', 'Closed', 'Waiting for User'])), name='it_tickets_status_valid'), models.CheckConstraint(condition=models.Q(('resolution_time_hours__gte', 0), ('resolution_time_hours__isnull', True), _connector='OR'), name='it_tickets_resolution_valid')],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(default='user', max_length=20)),
            ],
            options={
                'db_table': 'users',
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['user', 'admin'])), name='users_role_valid')],
            },
        ),
    ]
