# Generated by Django 6.1 on 2026-08-15 20:52

import bcrypt
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_user_schema(apps, schema_editor):
    """Seed lookup roles, create the bootstrap administrator (poka) and
    migrate every legacy ``users`` row into the user / staff / login_count
    schema."""
    Role = apps.get_model('cyber', 'Role')
    User = apps.get_model('cyber', 'User')
    Staff = apps.get_model('cyber', 'Staff')
    LoginCount = apps.get_model('cyber', 'LoginCount')
    LegacyUser = apps.get_model('cyber', 'Users')

    admin_role, _ = Role.objects.get_or_create(role_name='Administrator')
    staff_role, _ = Role.objects.get_or_create(role_name='Normal Staff')

    poka, _ = User.objects.get_or_create(
        username='poka',
        defaults={
            'password_hash': bcrypt.hashpw(
                b'Pok@12345', bcrypt.gensalt()).decode('utf-8'),
            'role': admin_role,
            'is_active': True,
        },
    )
    Staff.objects.get_or_create(
        user=poka,
        defaults={
            'full_name': 'Poka Machande',
            'email': 'poka.machande@cyberintel.local',
            'position': 'System Administrator',
        },
    )
    LoginCount.objects.get_or_create(user=poka, defaults={'login_count': 0})

    admin_role.created_by = poka
    admin_role.updated_by = poka
    admin_role.save()
    staff_role.created_by = poka
    staff_role.updated_by = poka
    staff_role.save()

    for legacy in LegacyUser.objects.all():
        if User.objects.filter(username=legacy.username).exists():
            continue
        role = admin_role if legacy.role == 'admin' else staff_role
        user = User.objects.create(
            username=legacy.username,
            password_hash=legacy.password_hash,
            role=role,
            is_active=True,
            created_by=poka,
            updated_by=poka,
        )
        Staff.objects.create(
            user=user,
            full_name=legacy.username,
            created_by=poka,
            updated_by=poka,
        )
        LoginCount.objects.create(
            user=user,
            login_count=0,
            created_by=poka,
            updated_by=poka,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('auth_type', models.CharField(max_length=20)),
                ('status', models.CharField(default='success', max_length=20)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'auth',
            },
        ),
        migrations.CreateModel(
            name='LoginCount',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login_count', models.IntegerField(default=0)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login_count',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.RemoveConstraint(
            model_name='users',
            name='users_role_valid',
        ),
        migrations.AddField(
            model_name='aimonitorstate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='analyticalreports',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cyberincidents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='datasetsmetadata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ittickets',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='analyticalreports',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ittickets',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='cyber.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='staff',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='staff',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='logincount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='logincount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='logincount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_count', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='auth',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='auth',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='auth',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='aimonitorstate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='aimonitorstate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='analyticalreports',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='analyticalreports',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='cyberincidents',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='cyberincidents',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='datasetsmetadata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='datasetsmetadata',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='ittickets',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='cyber.user'),
        ),
        migrations.AddField(
            model_name='ittickets',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='cyber.user'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['full_name'], name='staff_full_na_bac223_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['email'], name='staff_email_090e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='auth',
            index=models.Index(fields=['auth_type'], name='auth_auth_ty_b36fde_idx'),
        ),
        migrations.AddIndex(
            model_name='auth',
            index=models.Index(fields=['status'], name='auth_status_b0a844_idx'),
        ),
        migrations.AddConstraint(
            model_name='auth',
            constraint=models.CheckConstraint(condition=models.Q(('auth_type__in', ['LOGIN', 'LOGOUT', 'FAILED'])), name='auth_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='auth',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['success', 'failure'])), name='auth_status_valid'),
        ),
        migrations.RunPython(
            code=seed_user_schema,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
