from django.db import migrations

# PostgreSQL cannot reorder columns with ALTER TABLE, so each table is rebuilt
# with the four audit columns (created_at, created_by, updated_at, updated_by)
# placed last. Constraints and indexes are captured first and recreated with
# their original names, and data is copied through, so the rebuild is lossless.


def _column_metadata(cur, table):
    cur.execute("""
        SELECT a.attname,
               format_type(a.atttypid, a.atttypmod) AS dtype,
               a.attnotnull,
               a.attidentity,
               pg_get_expr(d.adbin, d.adrelid) AS default_expr
        FROM pg_attribute a
        LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
        WHERE a.attrelid = to_regclass(%s)
          AND a.attnum > 0 AND NOT a.attisdropped
    """, (table,))
    return {row[0]: row for row in cur.fetchall()}


def _rebuild_table(cur, table, ordered_columns):
    quoted = '"{}"'.format(table)
    old = '"{}__old"'.format(table)
    meta = _column_metadata(cur, table)

    if 'id' in meta:
        cur.execute("SELECT pg_get_serial_sequence(%s, 'id')", (quoted,))
        old_seq = cur.fetchone()[0]
    else:
        old_seq = None

    # Local constraints (PK, unique, check, outbound FK).
    # Skip contype 'n' (named NOT NULL constraints): the rebuilt table declares
    # NOT NULL inline on every not-null column, so they must not be re-added.
    cur.execute("""
        SELECT conname, contype, pg_get_constraintdef(oid)
        FROM pg_constraint
        WHERE conrelid = to_regclass(%s)
          AND contype <> 'n'
    """, (table,))
    constraints = cur.fetchall()

    # Standalone indexes (excluding those backing PK/unique constraints).
    cur.execute("""
        SELECT indexdef
        FROM pg_indexes
        WHERE schemaname = 'public' AND tablename = %s
          AND indexname NOT IN (
              SELECT conname FROM pg_constraint
              WHERE conrelid = to_regclass(%s) AND contype IN ('p', 'u')
          )
    """, (table, table))
    index_defs = [row[0] for row in cur.fetchall()]

    # Inbound FKs (tables referencing this one).
    cur.execute("""
        SELECT conname, conrelid::regclass::text, pg_get_constraintdef(oid)
        FROM pg_constraint
        WHERE contype = 'f' AND confrelid = to_regclass(%s)
    """, (table,))
    inbound = cur.fetchall()

    # Self-referencing FKs are captured in `constraints` as well; only drop
    # FKs coming from other tables here.
    for conname, rel, _ in inbound:
        if rel == quoted:
            continue
        cur.execute(
            'ALTER TABLE {} DROP CONSTRAINT "{}"'.format(rel, conname))

    cur.execute('ALTER TABLE {0} RENAME TO {1}'.format(quoted, old))

    col_defs = []
    for name in ordered_columns:
        _, dtype, notnull, identity, default_expr = meta[name]
        parts = ['"{}" {}'.format(name, dtype)]
        if identity:
            parts.append('GENERATED BY DEFAULT AS IDENTITY')
        elif default_expr:
            parts.append('DEFAULT {}'.format(default_expr))
        if notnull:
            parts.append('NOT NULL')
        col_defs.append(' '.join(parts))

    cur.execute('CREATE TABLE {0} (\n    {1}\n)'.format(
        quoted, ',\n    '.join(col_defs)))

    cols = ', '.join('"{}"'.format(n) for n in ordered_columns)
    cur.execute('INSERT INTO {0} ({1}) SELECT {1} FROM {2}'.format(
        quoted, cols, old))

    cur.execute('DROP TABLE {0}'.format(old))

    if old_seq:
        cur.execute("SELECT pg_get_serial_sequence(%s, 'id')", (quoted,))
        new_seq = cur.fetchone()[0]
        if new_seq:
            cur.execute('SELECT count(*) FROM {0}'.format(quoted))
            row_count = cur.fetchone()[0]
            if row_count == 0:
                cur.execute('SELECT setval(%s, 1, false)', (new_seq,))
            else:
                cur.execute(
                    'SELECT setval(%s, (SELECT MAX(id) FROM {0}), true)'
                    .format(quoted), (new_seq,))
        if new_seq and new_seq != old_seq:
            cur.execute('ALTER SEQUENCE {0} RENAME TO "{1}"'.format(
                new_seq, old_seq.split('.')[-1]))

    # Re-add local constraints PK/unique/check first, FKs last, so every
    # referenced key exists before any foreign key is recreated.
    constraints.sort(key=lambda row: 1 if row[1] == 'f' else 0)
    for conname, _, condef in constraints:
        cur.execute(
            'ALTER TABLE {0} ADD CONSTRAINT "{1}" {2}'.format(
                quoted, conname, condef))
    for conname, rel, condef in inbound:
        if rel == quoted:
            continue
        cur.execute(
            'ALTER TABLE {0} ADD CONSTRAINT "{1}" {2}'.format(
                rel, conname, condef))
    for index_def in index_defs:
        cur.execute(index_def)


def reorder_audit_columns(apps, schema_editor):
    connection = schema_editor.connection
    tables = {
        'user': ['id', 'username', 'password_hash', 'role_id', 'is_active',
                 'last_login', 'created_at', 'created_by_id', 'updated_at',
                 'updated_by_id'],
        'roles': ['id', 'role_name', 'created_at', 'created_by_id',
                  'updated_at', 'updated_by_id'],
        'staff': ['id', 'user_id', 'full_name', 'email', 'phone', 'position',
                  'created_at', 'created_by_id', 'updated_at', 'updated_by_id'],
        'login_count': ['id', 'user_id', 'login_count', 'last_login_at',
                        'created_at', 'created_by_id', 'updated_at',
                        'updated_by_id'],
        'auth': ['id', 'user_id', 'username', 'auth_type', 'status',
                 'ip_address', 'user_agent', 'created_at', 'created_by_id',
                 'updated_at', 'updated_by_id'],
        'cyber_incidents': ['incident_id', 'timestamp', 'severity', 'category',
                            'status', 'description', 'created_at',
                            'created_by_id', 'updated_at', 'updated_by_id'],
        'datasets_metadata': ['dataset_id', 'name', 'row_count', 'column_count',
                              'uploaded_by', 'upload_date', 'created_at',
                              'created_by_id', 'updated_at', 'updated_by_id'],
        'it_tickets': ['ticket_id', 'priority', 'description', 'status',
                       'assigned_to', 'resolution_time_hours', 'created_at',
                       'created_by_id', 'updated_at', 'updated_by_id'],
        'audit_trail': ['id', 'user_id', 'action', 'resource', 'method',
                        'endpoint', 'ip_address', 'user_agent', 'session_id',
                        'status_code', 'response_time_ms', 'metadata',
                        'created_at', 'created_by_id', 'updated_at',
                        'updated_by_id'],
        'analytical_reports': ['id', 'run_id', 'question', 'answer',
                               'created_at', 'created_by_id', 'updated_at',
                               'updated_by_id'],
        'ai_monitor_state': ['key', 'value', 'created_at', 'created_by_id',
                             'updated_at', 'updated_by_id'],
    }
    order = ['user', 'roles', 'staff', 'login_count', 'auth',
             'cyber_incidents', 'datasets_metadata', 'it_tickets',
             'audit_trail', 'analytical_reports', 'ai_monitor_state']
    with connection.cursor() as cur:
        for table in order:
            _rebuild_table(cur, table, tables[table])


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0002_auth_restructure'),
    ]

    operations = [
        migrations.RunPython(
            code=reorder_audit_columns,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
