# app_model/reports.py
# Store and retrieve analytical reports generated by ai_monitor.py

from datetime import datetime

import pandas as pd


def create_reports_table(conn):
    from app_model.schema import create_analytical_reports_table
    create_analytical_reports_table(conn)


def add_analytical_report(conn, run_id, question, answer):
    cursor = conn.cursor()
    created_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    cursor.execute(
        """INSERT INTO analytical_reports (run_id, question, answer, created_at)
           VALUES (?, ?, ?, ?)""",
        (run_id, question, answer, created_at),
    )
    conn.commit()


def get_reports(conn, run_id=None, limit=None):
    sql = "SELECT * FROM analytical_reports"
    params = ()
    if run_id:
        sql += " WHERE run_id = ?"
        params = (run_id,)
    sql += " ORDER BY id DESC"
    if limit:
        sql += " LIMIT ?"
        params = params + (limit,)
    return pd.read_sql_query(sql, conn, params=params)


def get_report_runs(conn):
    sql = "SELECT DISTINCT run_id FROM analytical_reports ORDER BY run_id DESC"
    return pd.read_sql_query(sql, conn)
