# import all packages and functions
import streamlit as st
from app_model.db import get_connection
from app_model.reports import get_reports, get_report_runs
import pandas as pd

# setting the page
st.set_page_config(
    page_title="Analysis Reports",
    page_icon=":bar_chart:",
    layout="wide",
)

# set logged in session state as false
if 'logged_in' not in st.session_state:
    st.session_state.logged_in = False

# gate the page behind login
if not st.session_state.logged_in:
    st.write("Please log in to access the analysis reports.")
    if st.button("Go to Login Page"):
        st.session_state.logged_in = False
        st.switch_page("Home.py")
    st.stop()

st.title(":bar_chart: AI Analysis Reports")
st.subheader("Analytical reports generated by the AI monitor (refreshes automatically every 5 minutes).")


# The report section is a fragment that re-runs every 10 seconds, so new
# rows inserted by the scheduled AI monitor appear here automatically.
@st.fragment(run_every=10)
def display_reports():
    conn = get_connection()

    runs_df = get_report_runs(conn)

    if runs_df.empty:
        st.info("No analysis reports yet. The AI monitor will generate the first report soon.")
        return

    run_ids = runs_df["run_id"].tolist()
    latest_run = run_ids[0]

    # Show the most recent run first, allow browsing older runs
    selected_run = st.selectbox(
        "Select report run",
        run_ids,
        index=0,
        key="selected_report_run",
    )

    reports_df = get_reports(conn, run_id=selected_run)

    is_latest = selected_run == latest_run
    if is_latest:
        st.success(f"Latest report run: **{latest_run}** ({len(reports_df)} answers)")

    for _, row in reports_df.iterrows():
        with st.container(border=True):
            st.markdown(f"### {row['question']}")
            st.markdown(row["answer"])

    # Raw table of all runs for reference
    with st.expander("View raw reports table"):
        st.dataframe(get_reports(conn, limit=100))

    st.caption("This page refreshes automatically every 10 seconds. "
               "The AI monitor inserts a new report every 5 minutes.")


display_reports()
